image:
  repository: registry.digitalocean.com/wooshfood/carwash-booking
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: 50Mi
  requests:
    memory: 50Mi

ingress:
  enabled: true
  ingressClassName: nginx
  tls:
    enabled: true
    certManager: true