replicaCount: 1

image:
  repository: registry.digitalocean.com/wooshfood/carwash-booking
  tag: booking-dev-4191
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 250m
    memory: 200Mi
  requests:
    cpu: 250m
    memory: 200Mi

service:
  type: ClusterIP
  port: 80

containerPort: 3000  # Change if your app runs on a different port
