apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  NUXT_X_ODOO_API_KEY_QR: {{ .Values.secretEnv.NUXT_X_ODOO_API_KEY_QR | quote }}
  NUXT_X_ODOO_API_KEY_BOOKING: {{ .Values.secretEnv.NUXT_X_ODOO_API_KEY_BOOKING | quote }}
  NUXT_X_ODOO_API_KEY_LOYALTY: {{ .Values.secretEnv.NUXT_X_ODOO_API_KEY_LOYALTY | quote }}
